apiVersion: apps/v1
kind: Deployment
metadata:
    name: label-generator-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: label-generator
    template:
        metadata:
            labels:
                app: label-generator
        spec:
            containers:
                - name: label-generator
                  image: perroh/label-generator
                  env:
                      - name: PORT
                        value: "4000"

---
apiVersion: v1
kind: Service
metadata:
    name: label-generator-srv
spec:
    selector:
        app: label-generator
    ports:
        - name: label-generator
          protocol: TCP
          port: 4000
          targetPort: 4000
